<ManaImage>:
    size: sp(18), sp(18)
    canvas:
        Color:
            rgba: 1, 1, 1, 1
        Rectangle:
            texture: self.texture
            pos: self.pos
            size: sp(18), sp(18)

# <CachedImage>:
#     canvas:
#         Color:
#             rgba: self.color
#         Rectangle:
#             texture: self.texture
#             pos: self.pos
#             size: self.size
